# -*- coding: utf-8 -*-
"""pycaret-coryne.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/olsslucas/61048014ce9a4c7af38562fea6e51253/pycaret-coryne.ipynb

# Installation
"""

# run this cell to install pycaret in Google Colab
!pip install pycaret

# If you are using Jupyter notebook, you can pip install pycaret using jupyter notebook or command line
# pip install pycaret

from pycaret.utils import version
version()

"""# 1. Importing Dataset"""

import pandas as pd
data = pd.read_csv('data_coryne_2.csv')
data.info()
data

"""# 2. Setting up Environment"""

from pycaret.classification import *
clf1 = setup(data, target = 'Class', session_id=786)



"""# 3. Compare Models"""

compare_models()

"""# 4. Create Model"""

lr = create_model('lr')

dt = create_model('dt')

"""# 5. Tune Model"""

from pycaret.classification import *
tuned_lr = tune_model(lr)

print(tuned_lr)

lr_model = create_model('lr')
tuned_lr = tune_model(lr_model, optimize='AUC')

print(tuned_lr)

"""# 6. Ensemble Model"""

bagged_lr = ensemble_model(lr)

boosted_lr = ensemble_model(lr, method = 'Boosting')

"""# 7. Blend Models"""

lr = create_model('lr', verbose=False)

blender = blend_models(estimator_list=[lr], method = 'soft')

blender.estimators_

"""# 8. Analyze Model"""

plot_model(blender)

plot_model(blender, plot = 'confusion_matrix')

plot_model(blender, plot = 'pr')

plot_model(tuned_lr, plot = 'vc')

plot_model(lr, plot = 'boundary')

plot_model(tuned_lr, plot = 'boundary')

plot_model(blender, plot = 'boundary')

evaluate_model(lr)

"""# Learning Resources:

- PyCaret Classification Module : https://www.pycaret.org/classification
- Binary Classification Tutorial (Level Beginner) : https://pycaret.org/clf101/
- Binary Classification Tutorial (Level Intermediate) : https://pycaret.org/clf102/
- Kaggle Titanic Predictions (Video Tutorial) : https://www.youtube.com/watch?v=nqMM6rngNCA
"""